flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- HUnit-1.5.0.0
- QuickCheck-2.9.2
- StateVar-1.1.0.4
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.1
- base-orphans-0.5.4
- bifunctors-5.4.1
- call-stack-0.1.0
- clock-0.7.2
- comonad-5
- contravariant-1.4
- control-monad-exception-0.11.2
- distributive-0.5.2
- exceptions-0.8.3
- failure-0.2.0.3
- foldl-1.2.3
- hashable-1.2.5.0
- hostname-1.0
- hspec-2.4.2
- hspec-core-2.4.2
- hspec-discover-2.4.2
- hspec-expectations-0.8.2
- lifted-base-0.2.3.10
- managed-1.0.5
- monad-control-1.0.1.0
- monadloc-0.7.1
- mtl-2.2.1
- mwc-random-0.13.5.0
- optional-args-1.0.1
- optparse-applicative-0.13.1.0
- primitive-0.6.2.0
- profunctors-5.2
- quickcheck-io-0.1.4
- random-1.1
- semigroups-0.18.2
- setenv-0.1.1.3
- stm-2.4.4.1
- system-fileio-0.3.16.3
- system-filepath-0.4.13.4
- tagged-0.8.5
- temporary-1.2.0.4
- text-1.2.2.1
- tf-random-0.5
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- turtle-1.3.1
- unix-compat-0.4.3.1
- vector-0.12.0.0
- void-0.7.1
- ghc-paths-0.1.0.9
- syb-0.7
compiler-check: newer-minor
resolver: ghc-8.0.0
