flags:
  transformers-compat:
    five-three: true
extra-package-dbs: []
packages:
- .
extra-deps:
- data-bword-0.1.0.1
- data-sword-0.2.0.2
- exceptions-0.10.0
- hashable-1.2.7.0
- primitive-0.6.4.0
- transformers-compat-0.6.2
- vector-0.12.0.2
compiler-check: newer-minor
resolver: ghc-8.6.4
